# -  /ᴀᴅᴀᴍ x ʙᴏᴛ/

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/Janith-max/ADAM-BOT /root/Janith-max
WORKDIR /root/Janith-max/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /ᴀᴅᴀᴍ x ʙᴏᴛ/
